name: Bug report
description: Report a bug.
assignees: ManuelSchneid3r
labels: ["Needs triage"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to file this bug. 
      Please make sure this issue does not exist yet. 
- type: dropdown
  id: Source
  attributes:
    label: Source
    description: Where did you get the build from?
    options:
      - Open Build Service 
      - Homebrew
      - AUR
      - From source
      - Other (leave a note)
    default: 0
  validations:
    required: true
- type: dropdown
  id: Component
  attributes:
    label: Component
    description: Which component is affected?
    options:
      - App
      - Plugin
      - CI/CD
    default: 0
  validations:
    required: true
- type: textarea
  attributes:
    label: App logs
    description: Run Albert from terminal using the command below, reproduce the issue and post the output here.
    render: markdown
    placeholder: |
      # Linux
      QT_LOGGING_RULES='albert*=true' albert --platform xcb
      # macOS
      QT_LOGGING_RULES='albert*=true' /Applications/Albert.app/Contents/MacOS/albert
  validations:
    required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: Anything that will give more context about the issue you are encountering!
  validations:
    required: false
    
